# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "headed" do |c|
    c.vm.box = "ubuntu/xenial64"

    # Provision with AdFisher dependencies
    c.vm.provision :shell, path: "bootstrap.sh", args: "headed"

    c.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 4
      v.gui = true
    end
  end

  # Headless VM should require lesser resources and may be necessary for running AdFisher on
  # weak computers.
  config.vm.define "headless" do |c|
    c.vm.box = "ubuntu/xenial64"

    # Provision with AdFisher dependencies
    c.vm.provision :shell, path: "bootstrap.sh", args: "headless"

    c.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 4
      v.gui = false
    end
  end

end
